name: Quality

on: pull_request

jobs:
  commitlint:
    name: 'Commitlint'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run commitlint check
        run: npm exec commitlint -- -f ${{ github.event.pull_request.base.sha }}

  eslint:
    name: 'ESLint'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run ESLint check
        run: npm run eslint-check

  prettier:
    name: 'Prettier'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run Prettier check
        run: npm run prettier-check
